Add other

diff --git a/.github/workflows/pr-linter.yml b/.github/workflows/pr-linter.yml
--- a/.github/workflows/pr-linter.yml
+++ b/.github/workflows/pr-linter.yml
@@ -23,8 +23,8 @@ jobs:
             exit 1
           fi
           
-          if ! [[ "$PR_BRANCH" =~ ^(bug|feature)/ ]]; then
-            echo "::error::Branch name must start with 'bug/' or 'feature/'."
+          if ! [[ "$PR_BRANCH" =~ ^(bug|feature|other)/ ]]; then
+            echo "::error::Branch name must start with 'bug/' or 'feature/' or 'other/'."
             exit 1
           fi
 
